Controllers/CourseController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Security.Claims;
using UniversityProject.Entities;
using UniversityProject.Interfaces;
using UniversityProject.Models;
using UniversityProject.Services;

namespace UniversityProject.Controllers
{
    public class CourseController : Controller
    {
        private readonly ICourseService _courseService;
        private readonly ITeacherService _teacherservice;
        private readonly SignInManager<User> _signInManager;
        private readonly UserManager<User> _userManager;
        private readonly IUserCourseService _userCourseService;
        private readonly IImageService _imageService;
        public CourseController(
            IImageService imageService,
            ICourseService courseService,
            UserManager<User> userManager,
            ICourseService lessonService,
            ITeacherService teacherservic,
            SignInManager<User> signInManager,
            IUserCourseService userCourseService)
        {
            _courseService = lessonService;
            _teacherservice=teacherservic;
            _signInManager = signInManager;
            _userManager = userManager;
            _courseService=courseService;
            _userCourseService = userCourseService;
            _imageService=imageService;
        }

        public async Task<IActionResult> Index(string query = null)
        {
            IEnumerable<Course> courses = null;
            var courseListVMs = new List<CourseListVM>();
            var user = await _signInManager.UserManager.GetUserAsync(User);
            if (!string.IsNullOrEmpty(query) && query.Length < 3)
            {
                // Handle cases where the query is too short or empty
                ViewBag.ErrorMessagequery =null;
                ViewBag.ErrorMessagequery = "Search query must be at least 3 characters long.";
            }
            if (query != null && query.Length>=3)
            {
                courses = (await _courseService.SearchCourses(query)).OrderByDescending(c => c.CreatedOn).ToList();
                ViewBag.ErrorMessage = "Search Courses  Like "+query;

            }

            if (courses == null)
            {
                courses = (await _courseService.GetAllAsync()).OrderByDescending(c => c.CreatedOn).ToList();

            }

            foreach (var course in courses)
            {
                int studentNumbr = await _userCourseService.CalculateStudentCount(course.Id);
                var courseListVM = new CourseListVM
                {
                    Id = course.Id,
                    Name = course.Name,
                    Description = course.Description,
                    TeacherName = course.Teacher != null ? course.Teacher.Name : null, // Assuming Teacher has a Name property
                    Cost = course.Cost,
                    IsDeleted = course.IsDeleted,
                    IsActive = course.IsActive,
                    CreatedOn = course.CreatedOn,
                    Image = course.Image,
                    ImageId = course.ImageId,
                    Days = course.Days,
                    StartTime = course.StartTime,
                    EndTime=course.EndTime,
                    StartDate = course.StartDate,
                    EndDate = course.EndDate,
                    IsExist= user==null ? true : await _userCourseService.CourseIsExistForUser(user.Id, course.Id),
                    StudentNumber = studentNumbr,

                };
                courseListVMs.Add(courseListVM);
            }
            return View(courseListVMs);
        }


        public async Task<IActionResult> Details(Guid id)
        {
            var lesson = await _courseService.GetByIdAsync(id);
            if (lesson == null)
            {
                return NotFound();
            }
            return View(lesson);
        }

        public async Task<IActionResult> Create()
        {
            var courseVM = new AddCourseVm();
            var user = await _signInManager.UserManager.GetUserAsync(User);
            if (user.IssystemAdmin)
            {
                var teachers = await _teacherservice.GetAllAsync();
                courseVM.Teachers = teachers.ToList();
                ViewBag.TeacherList = new SelectList(courseVM.Teachers, "Id", "Name");
                return View(courseVM);
            }
            else
            {
                var teacher = await _teacherservice.GetByIdUser(user.Id);
                if (teacher!=null)
                {
                    courseVM.Teachers = new List<Teacher> { teacher };
                    ViewBag.TeacherList = new SelectList(courseVM.Teachers, "Id", "Name");
                    return View(courseVM);
                }
            }
            TempData["AlertMessage"] = "User Is not Teacher";
            return RedirectToAction("Index");

        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(AddCourseVm addCourseVM)
        {
            var courseVM = new AddCourseVm();
            var user = await _signInManager.UserManager.GetUserAsync(User);

            if (!ModelState.IsValid)
            {
                if (user.IssystemAdmin)
                {
                    var teachers = await _teacherservice.GetAllAsync();
                    courseVM.Teachers = teachers.ToList();
                    ViewBag.TeacherList = new SelectList(courseVM.Teachers, "Id", "Name");
                    return View(courseVM);
                }
                else
                {
                    var teacher = await _teacherservice.GetByIdUser(user.Id);
                    if (teacher!=null)
                    {
                        courseVM.Teachers = new List<Teacher> { teacher };
                        ViewBag.TeacherList = new SelectList(courseVM.Teachers, "Id", "Name");
                        return View(courseVM);
                    }
                }
                return View(addCourseVM);
            }
            var course = new Course();
            var teacherId = new Guid();

            if (user.IssystemAdmin)
            {
                teacherId=addCourseVM.SelectedTeacherId;
            }
            else
            {
                teacherId = (await _teacherservice.GetByIdUser(user.Id)).Id;
            }
            if ((addCourseVM.Image != null && addCourseVM.Image.Length > 0))
            {
                int imageType = 1;
                var imageTypeId = await _imageService.GetImageType(imageType);
                var result = await _imageService.AddAsync(addCourseVM.Image, imageTypeId);
                if (result.Isvalid)
                {
                    course.ImageId= result.resultId;
                }
            }
            var selectedDays = new List<DayOfWeek>();
            if (addCourseVM.Sunday) selectedDays.Add(DayOfWeek.Sunday);
            if (addCourseVM.Monday) selectedDays.Add(DayOfWeek.Monday);
            if (addCourseVM.Tuesday) selectedDays.Add(DayOfWeek.Tuesday);
            if (addCourseVM.Wednesday) selectedDays.Add(DayOfWeek.Wednesday);
            if (addCourseVM.Thursday) selectedDays.Add(DayOfWeek.Thursday);
            if (addCourseVM.Friday) selectedDays.Add(DayOfWeek.Friday);
            if (addCourseVM.Saturday) selectedDays.Add(DayOfWeek.Saturday);


            course.Days=selectedDays;
            course.StartTime=addCourseVM.StartTime;
            course.EndDate=addCourseVM.EndDate;
            course.StartDate=addCourseVM.StartDate;
            course.Cost=addCourseVM.Cost;
            course.Name=addCourseVM.Name;
            course.TeacherId=teacherId;
            course.IsActive=addCourseVM.IsActive;
            course.Description=addCourseVM.Description;
            course.EndTime=addCourseVM.EndTime;
            await _courseService.AddAsync(course);
            return RedirectToAction(nameof(Index));

        }

        public async Task<IActionResult> Edit(Guid id)
        {
           
            var course = await _courseService.GetByIdAsync(id);
            if (course == null)
            {
                return NotFound();
            }


            

            // Map Course entity to AddCourseVm
            var addCourseVm = new AddCourseVm
            {
                Id = course.Id,
                Name = course.Name,
                Description = course.Description,
                SelectedTeacherId = course.TeacherId,
                Cost = course.Cost,
                IsActive = course.IsActive,
                StartDate = course.StartDate,
                EndDate = course.EndDate,
                StartTime = course.StartTime,
                EndTime = course.EndTime,
                Sunday = course.Days.Contains(DayOfWeek.Sunday),
                Monday = course.Days.Contains(DayOfWeek.Monday),
                Tuesday = course.Days.Contains(DayOfWeek.Tuesday),
                Wednesday = course.Days.Contains(DayOfWeek.Wednesday),
                Thursday = course.Days.Contains(DayOfWeek.Thursday),
                Friday = course.Days.Contains(DayOfWeek.Friday),
                Saturday = course.Days.Contains(DayOfWeek.Saturday),
                //Teachers = await _teacherService.GetAllTeachersAsync() // Assuming you have a method to get all teachers
            };
            var teacher = await _teacherservice.GetByIdAsync(course.TeacherId);
            if (teacher!=null)
            {
                addCourseVm.Teachers = new List<Teacher> { teacher };
                ViewBag.TeacherList = new SelectList(addCourseVm.Teachers, "Id", "Name");
                return View(addCourseVm);
            }
            return View(addCourseVm);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, AddCourseVm addCourseVm)
        {

Controllers/UserController.cs
using Microsoft.AspNetCore.Mvc;
using UniversityProject.Entities;
using UniversityProject.Interfaces;
using UniversityProject.Models;


namespace UniversityProject.Controllers
{
    public class UserController : Controller
    {
        private readonly IUserService _userService;
        private readonly IImageService _imageService;
        private readonly ITeacherService _teacherService;

        public UserController(IUserService userService, IImageService imageService, ITeacherService teacherService)
        {
            _userService = userService;
            _imageService = imageService;
            _teacherService = teacherService;
        }

        public async Task<IActionResult> Index()
        {
            var users = await _userService.GetAllAsync();
            return View(users);
        }

        public async Task<IActionResult> Edit(Guid id)
        {
            var user = await _userService.GetByIdAsync(id);
            if (user == null)
            {
                return NotFound();
            }

            var model = new EditUserVM
            {
                Id = user.Id,
                Firstname = user.Firstname,
                Lastname = user.Lastname,
                Birthdate = user.Birthdate,
                IssystemAdmin = user.IssystemAdmin,
                IsDeleted = user.IsDeleted,
                IsModified = user.IsModified
            };

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, EditUserVM model)
        {
            if (id != model.Id)
            {
                return BadRequest();
            }

            if (ModelState.IsValid)
            {
                await _userService.UpdateAsync(model);
                return RedirectToAction(nameof(Index));
            }
            return View(model);
        }

        public async Task<IActionResult> Delete(Guid id)
        {
            var user = await _userService.GetByIdAsync(id);
            if (user == null)
            {
                return NotFound();
            }

            await _userService.DeleteAsync(id);
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> CreateTeacher(Guid userId)
        {
            var user = await _userService.GetByIdAsync(userId);
            if (user == null)
            {
                return RedirectToAction("Index");
            }

            user.IsTeacher = true;
            await _userService.UpdateAsync(new EditUserVM
            {
                Id = user.Id,
                Firstname = user.Firstname,
                Lastname = user.Lastname,
                Birthdate = user.Birthdate,
                IssystemAdmin = user.IssystemAdmin,
                IsDeleted = user.IsDeleted,
                IsModified = true
            });

            var teacher = new Teacher
            {
                UserId = user.Id,
                Name = user.Firstname + " " + user.Lastname,
                IsActive = true
            };

            await _teacherService.AddAsync(teacher);

            return RedirectToAction("Index");
        }
    }
}

Views/Shared/_Alert.cshtml
@if (TempData["AlertMessage"] != null)
{
    <div class="alert alert-@TempData["AlertType"] alert-dismissible fade show" role="alert">
        @TempData["AlertMessage"]
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
}

Views/Shared/_Layout.cshtml
<!doctype html>
<html lang="en">
@using Microsoft.AspNetCore.Identity
@inject SignInManager<UniversityProject.Entities.User> SignInManager
@inject UserManager<UniversityProject.Entities.User> UserManager

@{
    ViewData["Title"] = "Home";
    var isAuthenticated = User.Identity.IsAuthenticated;
    UniversityProject.Entities.User currentUser = null;
    if (isAuthenticated)
    {
        currentUser = await UserManager.GetUserAsync(User);

    }
}
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>  @ViewData["Title"]</title>

    <link rel="shortcut icon" href="~/assets/images/fav.jpg">
    <link rel="stylesheet" href="~/assets/css/bootstrap.min.css">
    <link rel="stylesheet" href="~/assets/css/fontawsom-all.min.css">
    <link rel="stylesheet" href="~/assets/plugins/slider/css/owl.carousel.min.css">
    <link rel="stylesheet" href="~/assets/plugins/slider/css/owl.theme.default.css">
    <link rel="stylesheet" type="text/css" href="~/assets/css/style.css" />

    <meta charset="utf-8">
    <title>Calendar</title>
    <meta name="viewport"
          content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet"
          href="https://fonts.googleapis.com/css2?family=Material+Symbols+Rounded:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200">
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet" />

</head>

<body>

    <!-- ################# Header Starts Here#######################--->
    <header>
        <div class="header-top">
            <div class="container">
                <div class="row">
                    <div class="col-lg-7 col-md-12 left-item">
                        <ul style="color: white;">
                       
                          
                                @if (SignInManager.IsSignedIn(User))
                                {
                                <li class="nav-item">
                                    <span>  <a class="dropdown-item" asp-controller="Account" asp-action="Login" style="color: white;"  asp-area=""> @User.Identity.Name</a></span>
                                </li>
                                }
                                else
                                {
                                <li class="nav-item">
                                    <a class="dropdown-item" asp-controller="Account" style="color: white;" asp-action="Login" asp-area="">Login</a>
                                </li>
                                }


                  
                        </ul>

                        <ul>
                            <li><i class="fas fa-envelope-square"></i> University@ashkanr2.ir</li>
                            <li><i class="fas fa-phone-square"></i> 09134434742 -- 09203625752</li>
                        </ul>
                    </div>
                    <div class="col-lg-5 d-none d-lg-block right-item">
                        <ul>
                            <li><a><i class="fab fa-github"></i></a></li>
                            <li><a><i class="fab fa-google-plus-g"></i></a></li>
                            <li> <a><i class="fab fa-pinterest-p"></i></a></li>
                            <li><a><i class="fab fa-twitter"></i></a></li>
                            <li> <a><i class="fab fa-facebook-f"></i></a></li>

                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <div id="nav-head" class="header-nav">
            <div class="container">
                <div class="row">
                    @* <div class="col-md-3 col-sm-12 nav-img">
                        <img src="~/assets/images/allamehlogo.jpg" alt="">
                        <a data-toggle="collapse" data-target="#menu" href="#menu"><i class="fas d-block d-md-none small-menu fa-bars"></i></a>
                   </div> *@
                    <div id="menu" class="col-md-9 d-none d-md-block nav-item">
                        <ul>
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Course" asp-action="Index">Courses</a>
                            </li>
                            @if (isAuthenticated && ( !currentUser.IssystemAdmin))
                            {
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Course" asp-action="MyCourses">MyCourse</a>
                            </li>
                            }
                            @if (isAuthenticated && ( currentUser.IssystemAdmin))
                                {
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="User" asp-action="Index">Users</a>
                            </li>
                                }
                            @* @if (isAuthenticated && (currentUser.IssystemAdmin))
                            {
                                <li class="nav-item">
                                    <a class="nav-link" asp-area="" asp-controller="CourseTime" asp-action="Index">semester</a>
                                </li>
                            }
                        @*     <li class="nav-item">
                                <!-- Move the search form outside the list -->
                                <form asp-controller="Home" asp-action="Search" method="get" >
                                    <div class="input-group">
                                        <input class="form-control" type="search" placeholder="Search" aria-label="Search" name="query">
                                        <button class="btn btn-outline-success" type="submit">Search</button>
                                    </div>
                                </form>
                            </li> *@
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </header>

    <!-- ################# Slider Starts Here#######################--->

    @RenderBody()
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />


    <!-- ################# Key Features Starts Here#######################--->
    <!-- ################# popular Cources Starts Here#######################--->
    <!-- ################# University Number Starts Here#######################--->
    <!-- ################# Our Instructors Starts Here#######################--->
    <!-- ################# Our Blog Starts Here#######################--->
    <!-- ################# Our Footer Starts Here#######################--->


    <footer>
        <div class="container">
            <div class="row">
                <div class="col-md-3 about">
                    <h2>About Us</h2>
                    <p>Phasellus scelerisque ornare nisl sit amet pulvinar. Nunc non scelerisque augue. Proin et sollicitudin velit. </p>

                    <div class="foot-address">
                        <div class="icon">
                            <i class="fas fa-map-marker-alt"></i>
                        </div>
                        <div class="addet">
                            BlueDart
                            Marthandam (K.K District)
                            Tamil Nadu, IND
                        </div>
                    </div>
                    <div class="foot-address">
                        <div class="icon">
                            <i class="far fa-envelope-open"></i>
                        </div>
                        <div class="addet">
                            info@smarteyeapps.com <br>
                            sales@smarteyeapps.com
                        </div>
                    </div>
                    <div class="foot-address">
                        <div class="icon">
                            <i class="fas fa-mobile-alt"></i>
                        </div>
                        <div class="addet">
                            +23 323 43434 <br>
                            +1 3232 434 55
                        </div>
                    </div>
                </div>
                <div class="col-md-3 fotblog">
                    <h2>From latest Blog</h2>
                    <div class="blohjb">
                        <p>dignissim. Integer tempor facilisis malesuada. Proin ac varius velit, tincidunt condimentum</p>
                        <span>22-1-2019</span>
                    </div>
                    <div class="blohjb">
                        <p>dignissim. Integer tempor facilisis malesuada. Proin ac varius velit, tincidunt condimentum</p>
                        <span>22-1-2019</span>
                    </div>
                    <div class="blohjb">
                        <p>dignissim. Integer tempor facilisis malesuada. Proin ac varius velit, tincidunt condimentum</p>
                        <span>22-1-2019</span>
                    </div>
                </div>
                <div class="col-md-3 glink">
                    <ul>
                        <li><a href="index.html"><i class="fas fa-angle-double-right"></i>Home</a></li>
                        <li><a href="about_us.html"><i class="fas fa-angle-double-right"></i>About Us</a></li>
                        <li><a href="services.html"><i class="fas fa-angle-double-right"></i>Services</a></li>
                        <li><a href="blog.html"><i class="fas fa-angle-double-right"></i>Blog</a></li>
                        <li><a href="pricing.html"><i class="fas fa-angle-double-right"></i>Gallery</a></li>
                        <li><a href="contact_us.html"><i class="fas fa-angle-double-right"></i>Contact Us</a></li>
                    </ul>
                </div>
                <div class="col-md-3 tags">
                    <h2>Easy Tags</h2>
                    <ul>
                        <li>Finance</li>
                        <li>Web Design</li>
                        <li>Internet Pro</li>
                        <li>Node Js</li>
                        <li>Java Swing</li>
                        <li>Angular Js</li>
                        <li>Vue Js</li>
                    </ul>
                </div>
            </div>
        </div>
    </footer>
    <div class="copy">
        <div class="container">
            <a href="https://www.smarteyeapps.com/">2015 &copy; All Rights Reserved | Designed and Developed by Smarteyeapps</a>

            <span>
                <a><i class="fab fa-github"></i></a>
                <a><i class="fab fa-google-plus-g"></i></a>
                <a><i class="fab fa-pinterest-p"></i></a>
                <a><i class="fab fa-twitter"></i></a>
                <a><i class="fab fa-facebook-f"></i></a>
            </span>
        </div>

    </div>

</body>

<script src="~/assets/js/jquery-3.2.1.min.js"></script>
<script src="~/assets/js/popper.min.js"></script>
<script src="~/assets/js/bootstrap.min.js"></script>
<script src="~/assets/plugins/slider/js/owl.carousel.min.js"></script>
<script src="~/assets/js/script.js"></script>



</html>